### ISSUE TITLE
admin  password ?  login failed

### ISSUE THREAD

**Issue by kissxrl** [hidu/proxy-manager#4]
admin psw
abc abc  

login failed

很好的软件...

后台无法登录,,试了几个密码都不行, 版本 是 0.21   最新的 0.22 在那里下载..谢谢了.

Current Version: 0.2.1

last version: 0.2.2

**Comment by hidu** [comment]
使用源码安装最新版本吧
你看看你的 conf/user 这个配置文件是否存在？帐号信息配置在这个文件中。
